# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM registry.access.redhat.com/ubi9/python-311

USER 0

RUN dnf update -y && \
    dnf install -y \
        autoconf \
        gcc \
        gcc-c++ \
        git \
        wget \
        make \
        cmake \
        ninja-build \
        python3-devel \
        bzip2 \
        bzip2-devel \
        libicu \
        libicu-devel && \
    dnf clean all && rm -rf /var/cache/dnf
    
        # Download and extract Boost
ARG BOOST_VERSION="1.85.0"
ARG BOOST_FILENAME="boost_${BOOST_VERSION//./_}"
RUN curl -L -o /tmp/boost.tar.gz https://sourceforge.net/projects/boost/files/boost/1.85.0/boost_1_85_0.tar.bz2/download && \
    ls -l /tmp/ && \
    tar -xjf /tmp/boost.tar.gz -C /opt && \
    rm /tmp/boost.tar.gz

# Build and install Boost
WORKDIR /opt/boost_1_85_0
RUN ./bootstrap.sh --with-libraries=filesystem,system,thread,regex,chrono,date_time --prefix=/usr/local && \
    ./b2 install

# Clean up build artifacts to reduce image size
WORKDIR /
RUN rm -rf /opt/boost_1_85_0

RUN pip3 install -U pip setuptools

# Install zlib system packages
RUN dnf install -y zlib zlib-devel && \
    dnf clean all && rm -rf /var/cache/dnf
